services:
  unit-test:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
      target: unit-test

  integration-test:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
      target: integration-test
    devices:
      - /dev/kvm

  daemon:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
      target: daemon
    devices:
      - /dev/kvm
    volumes:
      - andler-data:/var/lib/andler

  e2e:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
      target: e2e
    devices:
      - /dev/kvm

volumes:
  andler-data:
