use serde::{Deserialize, Serialize};

use crate::backend::BackendHandle;
use crate::fsm::InstanceState;
use crate::InstanceId;

/// Machine-readable event emitted by the daemon, forming the per-instance
/// audit trail. `ts_ms` is milliseconds since the UNIX epoch (wall clock).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DaemonEvent {
    pub ts_ms: u64,
    pub instance_id: Option<InstanceId>,
    pub kind: EventKind,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum EventKind {
    /// FSM transition, with the reason on failure-driven transitions.
    Lifecycle {
        from: InstanceState,
        to: InstanceState,
        reason: Option<String>,
    },

    /// State change of a long-running operation.
    Operation { op: Operation },

    /// Raw QEMU QMP event the daemon reacts to.
    Qmp { event: QmpEvent, data: String },

    /// Guest readiness contract reached.
    Readiness { level: GuestReadinessLevel },

    /// User-facing diagnostic line for the audit trail.
    Log {
        level: EventLogLevel,
        message: String,
    },
}

/// A raw QMP event forwarded from a backend, tagged with the handle of the
/// instance it belongs to. The daemon relay maps the handle back to an
/// instance id and republishes the event on the daemon bus.
#[derive(Debug, Clone)]
pub struct QmpEventRecord {
    pub handle: BackendHandle,
    pub event: QmpEvent,
    pub data: String,
}

/// Raw QEMU QMP events the daemon can react to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QmpEvent {
    VserportChanged,
    Shutdown,
    Reset,
    Powerdown,
    DeviceDeleted,
    BlockIoError,
    BlockJob,
    GuestPanicked,
    Watchdog,
    Stopped,
    Resumed,
    Other,
}

/// Steps of the guest readiness contract; ordered from weakest to strongest
/// guarantee.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum GuestReadinessLevel {
    SerialUp,
    QgaUp,
    DisplayApplied,
    GuestOsUp,
    WaydroidReady,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EventLogLevel {
    Error,
    Warn,
    Info,
    Debug,
    Trace,
}

/// Identifier of a long-running operation (uuid string, generated by the
/// daemon at enqueue time).
pub type OpId = String;

/// A long-running operation with phased progress. The daemon re-publishes the
/// same `Operation` under `EventKind::Operation` as it advances; phase/
/// progress bookkeeping lives in the operation runner (supervisor, phases
/// 2-3), this is the wire shape.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Operation {
    pub op_id: OpId,
    pub instance_id: InstanceId,
    pub kind: OperationKind,
    /// (phase name, weight) pairs; weights sum to <= 1.0.
    pub phases: Vec<(String, f32)>,
    /// Overall progress, 0.0..=1.0.
    pub progress: f32,
    pub state: OperationState,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OperationKind {
    Create,
    Clone,
    Start,
    Stop,
    SnapshotCreate,
    SnapshotRestore,
    SnapshotDelete,
    Compact,
    GuestInstall,
    GuestRemove,
    DiskCreate,
    DiskResize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OperationState {
    Queued,
    Running,
    Done,
    Failed,
    Cancelled,
}

impl DaemonEvent {
    /// Serializes to a single-line JSON record for the per-instance
    /// `events.jsonl` audit trail (append-only, rotated by size).
    pub fn to_jsonl_line(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }
}

impl Operation {
    pub fn new(kind: OperationKind, instance_id: InstanceId, op_id: OpId) -> Self {
        Operation {
            op_id,
            instance_id,
            kind,
            phases: Vec::new(),
            progress: 0.0,
            state: OperationState::Queued,
            error: None,
        }
    }

    pub fn finished(&self) -> bool {
        matches!(
            self.state,
            OperationState::Done | OperationState::Failed | OperationState::Cancelled
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_event() -> DaemonEvent {
        DaemonEvent {
            ts_ms: 1_700_000_000_000,
            instance_id: Some(InstanceId::new()),
            kind: EventKind::Lifecycle {
                from: InstanceState::Starting,
                to: InstanceState::Running,
                reason: None,
            },
        }
    }

    #[test]
    fn event_round_trips_through_json() {
        let event = sample_event();
        let json = serde_json::to_string(&event).expect("serialize");
        let restored: DaemonEvent = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, event);
    }

    #[test]
    fn operation_round_trips_through_json() {
        let op = Operation {
            op_id: "op-1".to_string(),
            instance_id: InstanceId::new(),
            kind: OperationKind::SnapshotCreate,
            phases: vec![("freeze".to_string(), 0.3), ("commit".to_string(), 0.7)],
            progress: 0.3,
            state: OperationState::Running,
            error: None,
        };
        let json = serde_json::to_string(&op).expect("serialize");
        let restored: Operation = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, op);
        assert!(!op.finished());
    }

    #[test]
    fn operation_states_are_serializable_and_ordered() {
        let json = serde_json::to_string(&GuestReadinessLevel::WaydroidReady).unwrap();
        assert_eq!(json, "\"WaydroidReady\"");
        assert!(GuestReadinessLevel::SerialUp < GuestReadinessLevel::WaydroidReady);
    }
}
