[package]
name = "andler-net"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
andler-core = { path = "../../core/andler-core" }
tokio = { workspace = true, features = ["process"] }
thiserror = { workspace = true }
async-trait = { workspace = true }



[lints]
workspace = true
