[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "andler"
path = "src/main.rs"

[dependencies]
andler-core = { path = "../core/andler-core" }
andler-rpc = { path = "../services/andler-rpc" }
tonic = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = "0.8"
dirs = { workspace = true }
