[package]
name = "andler-qemu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
andler-core = { path = "../../core/andler-core" }
andler-firmware = { path = "../../services/andler-firmware" }
andler-net = { path = "../../services/andler-net" }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures-core = "0.3"
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
libc = "0.2"
serde = { workspace = true }
serde_json = "1"
base64 = "0.22"
